name: movies
description: "An app to display the movies list"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  get_it: ^8.0.3
  connectivity_plus: ^6.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.0
  fluttertoast: ^8.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
